config/routes.rb
Lorcenter::Application.routes.draw do  
  
  mount Ckeditor::Engine => '/ckeditor'

  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots

  root 'static_pages#home' 

  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/doctor', to: 'static_pages#doctor', via: 'get'
  match '/doctor/semenov', to: 'static_pages#semenov', via: 'get'
  match '/doctor/gorbonosov', to: 'static_pages#gorbonosov', via: 'get'
  match '/price', to: 'static_pages#price', via: 'get'
  match '/rinoplastic', to: 'static_pages#rinoplastic', via: 'get'
  match '/lifting', to: 'static_pages#lifting', via: 'get'
  match '/hearaids', to: 'static_pages#hearaids', via: 'get'
  match '/preparation', to: 'static_pages#preparation', via: 'get'
  

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  #validates_attachment_presence :data
  #validates_attachment_size :data, :less_than => 100.megabytes
  #do_not_validate_attachment_file_type :data

  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  #validates_attachment_presence :data
  #validates_attachment_size :data, :less_than => 2.megabytes
  #validates_attachment_content_type :data, :content_type => /\Aimage/

  validates_attachment_content_type :data, :content_type => /\Aimage/
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data
  do_not_validate_attachment_file_type :data

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
 
  def home
  end

  def contact    
  end

  def about    
  end

  def doctor    
  end

  def semenov    
  end

  def price    
  end

  def rinoplastic    
  end

  def lifting    
  end

  def hearaids    
  end

  def preparation    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer" id="footer1">

  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12" id="footbc">
        <p><%= link_to "Главная", root_path %>&nbsp&nbsp&nbsp<%= link_to "О клинике", about_path %>&nbsp&nbsp&nbsp<%= link_to "Врачи", doctor_path %>&nbsp&nbsp&nbsp<%= link_to "Прайс-лист", price_path %>&nbsp&nbsp&nbsp<%= link_to "Контакты", contact_path %></p>
      </div>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <p>Лицензии на осуществление медицинской деятельности: № ЛО-23-01-003528 от 22.03.2001 и № 21-03-00245 от 12.03.2005</p>
      </div>

      <div class="col-md-4 col-sm-4 col-xs-12">
        <p>«ЛОР КЛИНИКА» Краснодар</p>
      </div> 
      <div class="col-md-4 col-sm-4 col-xs-12" id="footcontact">        
        <p>г. Краснодар, ул. Захарова, 59</p>                       
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12">
        <p>(861) 268-87-00, 268-78-73</p>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12">
        <p>© 2007-2014 Все права защищены</p>
      </div>
  </div>
</div>

  

  <% if Rails.env.production? %>  
  <!-- Yandex.Metrika counter -->
  
  <!-- /Yandex.Metrika counter -->
  <% end %>

</footer>

app/views/layouts/_header.html.erb
<!-- fixed navigation bar -->
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation" id="nbheader">
  
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#b-menu-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ЛОР КЛИНИКА</a>
      <!-- <a class="navbar-brand" rel="home" href="#" title="ЛОР КЛИНИКА">
        <%= image_tag "logo.png", style: "max-height: 40px;" %>
      </a> -->

    </div>
    <div class="collapse navbar-collapse" id="b-menu-1">
      <ul class="nav navbar-nav navbar-right">

        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Главная", root_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "О Клинике", about_path %></li>
        <li class="<%= 'active' if current_page?(doctor_path) %>"><%= link_to "Врачи", doctor_path %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Пациентам<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Услуги и цены", price_path %></li>
            <li><%= link_to "Подготовка к операции", preparation_path %></li>
          </ul>
        </li>

        <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Контакты", contact_path %></li>              

      </ul>
    </div> <!-- /.nav-collapse -->
  </div> <!-- /.container -->
  
</div> <!-- /.navbar -->
<!-- выпадающий список должен помещаться в рамках экрана -->
<script type="text/javascript">
  $('.dropdown-toggle').on("click", function() {
    var dropdownList = $('.dropdown-menu'),
    dropdownOffset = $(this).offset(),
    offsetLeft = dropdownOffset.left,
    dropdownWidth = dropdownList.width(),
    docWidth = $(window).width(),

    subDropdown = dropdownList.eq(1),
    subDropdownWidth = subDropdown.width(),

    isDropdownVisible = (offsetLeft + dropdownWidth <= docWidth),
    isSubDropdownVisible = (offsetLeft + dropdownWidth + subDropdownWidth <= docWidth);

    if (!isDropdownVisible || !isSubDropdownVisible) {
          dropdownList.css("right", "0").css("left", "auto");
    } else {
          dropdownList.css("right", "auto").css("left", "0");
    }
  });

  $('.dropdown-toggle').hover(function() {
    var dropdownList = $('.dropdown-menu'),
    dropdownOffset = $(this).offset(),
    offsetLeft = dropdownOffset.left,
    dropdownWidth = dropdownList.width(),
    docWidth = $(window).width(),

    subDropdown = dropdownList.eq(1),
    subDropdownWidth = subDropdown.width(),

    isDropdownVisible = (offsetLeft + dropdownWidth <= docWidth),
    isSubDropdownVisible = (offsetLeft + dropdownWidth + subDropdownWidth <= docWidth);

    if (!isDropdownVisible || !isSubDropdownVisible) {
          dropdownList.css("right", "0").css("left", "auto");
    } else {
          dropdownList.css("right", "auto").css("left", "0");
    }
  }, function() {
    // обработчик отведения мыши
  });

</script>

app/views/layouts/_mainheader.html.erb
<div class="jumbotron">

  <p class="imgprino"><%= image_tag "main_banner.jpg", class: "img-responsive imgd" %></p>

  <h1>«ЛОР КЛИНИКА» Краснодар - медицина высоких технологий</h1>
  
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-12 divbase">      
        <h2><%= image_tag "64spiegel.png", style: "max-width:50px" %> Отделение оториноларингологии</h2>
        <h2><%= image_tag "plastic_man.png", style: "max-width:43px" %> Отделение пластической хирургии</h2>
      </div>     
      <div class="col-md-6 col-sm-6 col-xs-12 divbase">        
        <h3 class="h3noundertel">Справки по телефонам</h3>
        <h2 style="margin-bottom:8px;"><%= image_tag "phone.png", style: "max-width:25px" %> <span>8 (861)</span> 268-87-00, 268-78-73</h2>
        <h2><%= image_tag "marker_boll.png", style: "max-width:30px" %>г. Краснодар, ул. Захарова, 59</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <h3 class="h3nounder" style="margin-bottom:12px;">Клиника предоставляет услуги пациентам всех возрастных категорий и жителям других регионов</h3>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12">      
        <p class="imgprino"><%= image_tag "ears.png", class: "img-responsive img-thumbnail" %></p>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12">
        <p class="imgprino"><%= image_tag "throat.png", class: "img-responsive img-thumbnail" %></p>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12">      
        <p class="imgprino"><%= image_tag "nose.png", class: "img-responsive img-thumbnail" %></p>
      </div>
    </div>    

    <hr>  
    
    <div class="row">
      
      <div class="col-md-4 col-sm-4 col-xs-12">       
        <div class="block1">
          <div class="block_header clearfix">
            <div class="block_title">
              <h3 class="h3nounder">Приём ведут</h3>
            </div>
          </div>
          <div class="best">
            <div class="block_body">
              <ul class="mhul">
                <li><span class="glyphicon glyphicon-tags"></span> врачи высшей категории</li>
                <li><span class="glyphicon glyphicon-tags"></span> кандидаты медицинских наук</li>
                <li><span class="glyphicon glyphicon-tags"></span> доценты</li>
                <li><span class="glyphicon glyphicon-tags"></span> профессор</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4 col-sm-4 col-xs-12">        
        <div class="block1">
          <div class="block_header clearfix">
            <div class="block_title">
                <h3 class="h3nounder">Время приёма</h3>
            </div>
          </div>
          <div class="best">
            <div class="block_body">          
              <ul class="mhul">
                <li><span class="glyphicon glyphicon-time"></span> <b>Понедельник - Пятница</b><br>с 8.00 до 19.00</li>
                <li><span class="glyphicon glyphicon-time"></span> <b>суббота</b><br>с 8.00 до 13.00</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4 col-sm-4 col-xs-12">        
        <div class="block1">
          <div class="block_header clearfix">
            <div class="block_title">
              <h3 class="h3nounder">Направления</h3>
            </div>
          </div>
          <div class="best">
            <div class="block_body"> 
              <ul class="mhul">
                <li><span class="glyphicon glyphicon-pushpin"></span> лор-болезни</li>
                <li><span class="glyphicon glyphicon-pushpin"></span> ринопластика</li>
                <li><span class="glyphicon glyphicon-pushpin"></span> пластическая хирургия</li>
                <li><span class="glyphicon glyphicon-pushpin"></span> оперативные вмешательства</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

    </div>

    <hr>

    <div class="row">    
      <div class="col-md-12 col-sm-12 col-xs-12">      
        <h3 class="h3nounder">Функционирует аудиометрический кабинет (3 врача сурдолога)</h3>
        <p class="imgprino"><%= image_tag "audilogist.png", class: "img-responsive img-thumbnail" %></p>
      </div>      
    </div>

  </div>
</div> <!-- end jumbotron -->

<div class="intro-marketing">
  <div class="container">    
    <div class="row" id="div_border_bottom">
      <!-- <div class="col-md-12 col-sm-12 col-xs-12">
        <h2 class="cental">Предоставляемые услуги</h2>
      </div> -->
      
      <div class="col-md-4 col-sm-6 col-xs-12">     
        <h3>Слуховые аппараты</h3>
        <p class="imgprino"><%= image_tag "ha_main.jpg", class: "img-responsive img-thumbnail" %></p>
        <ul class="mhul1">
          <li><span class="glyphicon glyphicon-ok"></span> <span>консультации высококвалифицированных специалистов по вопросам слухопротезирования</span></li>
          <li><span class="glyphicon glyphicon-ok"></span> <span>полное аудиологическое обследование детей и взрослых</span></li>
          <li><span class="glyphicon glyphicon-ok"></span> <span>подбор слуховых аппаратов, регулировка СА на компьютере</span></li>
        </ul>
        <p style="text-align:center;"><a role="button" href="/hearaids" class="btn btn-clear">Подробнее</a></p>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-12">      
        <h3>Круговая подтяжка лица (Лифтинг)</h3>
        <p class="imgprino"><%= image_tag "facelift_main.jpg", class: "img-responsive img-thumbnail" %></p>
        <p><span>Подтяжка лица сегодня уже не является некой диковинкой, как это было совсем недавно. Как и другие пластические процедуры, она доступна всем, желающим сохранить свой внешний вид неизмененным в течение многих лет. Современные методики позволяют нашим пациентам выглядеть более естественно, так как они выглядели 5-10 лет назад.</span></p>
        <p style="text-align:center;"><a role="button" href="/lifting" class="btn btn-clear">Подробнее</a></p>
      </div> 
      <div class="col-md-4 col-sm-6 col-xs-12">      
        <h3>Корекция формы носа (Ринопластика)</h3>
        <p class="imgprino"><%= image_tag "rino_main.jpg", class: "img-responsive img-thumbnail" %></p>
        <p><span>Пластикой носа в ЛОР КЛИНИКЕ занимаются в течение десятилетий.</span></p>
        <p><span>Залогом успеха является сочетание глубоких знаний в области теории пластической хирургии и накапливаемый с годами опыт, что позволяет получить предсказуемые результаты.</span></p>
        <p style="text-align:center;"><a role="button" href="/rinoplastic" class="btn btn-clear">Подробнее</a></p>
      </div>

    </div>
  </div>
</div>



<div class="intro-otdelenie">
  <div class="container">   
    <div class="row" id="div_border_bottom">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <h2 class="cental">Приоритетные направления работы клиники</h2>
      </div> 

      
      <div class="col-md-6 col-sm-6 col-xs-12">        
        
          <p class="imgprino"><%= image_tag "oto_rino_throat.jpg", class: "img-responsive img-thumbnail" %></p>
          <h3>Отделение оториноларингологии</h3>
          <ul class="mhul-ot">
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Аденоиды", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Восстановление проходимости слезных путей", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Врач вестибулолог (лечение головокружения)", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Искривления носовой перегородки", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Лазерная хирургия", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Лечение храпа", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Микрохирургия гортани", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Синуситы (Гайморит)", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Слух: Имплантируемые слуховые аппараты костной проводимости", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Слух: Кохлеарная имплантация", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Слухоулучшающая хирургия", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Слух: Подбор слуховых аппаратов", hearaids_path %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Эндоскопическая хирургия носа и околоносовых пазух", "#" %></span></li>
          </ul>
        
      </div>       
      <div class="col-md-6 col-sm-6 col-xs-12">
              
          <p class="imgprino"><%= image_tag "plastic_surg_ban.jpg", class: "img-responsive img-thumbnail" %></p>
          <h3>Отделение пластической хирургии</h3>
          <ul class="mhul-ot">
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Дермабразия", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Контурная пластика", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Липосакция", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Лицевые протезы (нос, ушные раковины, глаза)", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Операции на веках", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Пластика подбородка", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Пластика ушных раковин", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Подтяжка лица", lifting_path %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Ринопластика", rinoplastic_path %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Удаление новообразований кожи", "#" %></span></li>
            <li><span class="glyphicon glyphicon-ok"></span> <span><%= link_to "Устранение морщин", "#" %></span></li>            
          </ul>
                             
      </div>

    </div>
  </div>
</div>

app/views/layouts/_shablon.html.erb
<!-- 2-column layout -->
<div class="row row-offcanvas row-offcanvas-right">
  <div class="col-md-9">

    <!-- jumbotron -->
    <div class="jumbotron">
      <h1>Lorem ipsum</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet tempus massa. Nam quis purus sit amet augue iaculis dapibus non in nisi. Sed sed volutpat neque. Nulla posuere.</p>
      <p><a role="button" href="#" class="btn btn-lg btn-success">Sign up today</a></p>
    </div>

    <div class="row">

      <!-- column 1 -->
      <div class="col-sm-6">

        <!-- box 1 -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Panel 1 title</h3>
          </div>
          <div class="panel-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet tempus massa. Nam quis purus sit amet augue iaculis dapibus non in nisi. Sed sed volutpat neque. Nulla posuere.</p>
            <p><a class="btn btn-default right" href="#" role="button">Continue &raquo;</a></p>
          </div>
        </div>

        <!-- box 2 -->
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Panel 2 title</h3>
          </div>
          <div class="panel-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet tempus massa. Nam quis purus sit amet augue iaculis dapibus non in nisi. Sed sed volutpat neque. Nulla posuere.</p>
            <p><a class="btn btn-default right" href="#" role="button">Continue &raquo;</a></p>
          </div>
        </div>
      </div> <!-- /column 1 -->

      <!-- column 2 -->
      <div class="col-sm-6">

        <!-- box 3 -->
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Panel 3 title</h3>
          </div>
          <div class="panel-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet tempus massa. Nam quis purus sit amet augue iaculis dapibus non in nisi. Sed sed volutpat neque. Nulla posuere.</p>
            <p><a class="btn btn-default right" href="#" role="button">Continue &raquo;</a></p>
          </div>
        </div>

        <!-- box 4 -->
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Panel 4 title</h3>
          </div>
          <div class="panel-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet tempus massa. Nam quis purus sit amet augue iaculis dapibus non in nisi. Sed sed volutpat neque. Nulla posuere.</p>
            <p><a class="btn btn-default right" href="#" role="button">Continue &raquo;</a></p>
          </div>
        </div>
      </div> <!-- /column 2 -->

    </div><!--/row-->
  </div><!--/span-->

  <!-- column 3 (sidebar) -->
  <div class="col-md-3" id="sidebar">
    <div class="list-group" role="navigation">
      <a href="#" class="list-group-item">Link</a>
      <a href="#" class="list-group-item">Link</a>
      <a href="#" class="list-group-item active">Link</a>
      <a href="#" class="list-group-item">Link</a>
      <a href="#" class="list-group-item">Link</a>
    </div>

    <!-- box 5 -->
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">Form elements</h3>
      </div>
      <div class="panel-body">
        <form role="form">
          <div class="form-group">
            <label for="emailField">Email address</label>
            <input type="email" class="form-control" id="emailField" placeholder="Enter email">
          </div>
          <div class="form-group">
            <label for="selectField">Type</label>
            <select class="form-control" id="selectField">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
          </div>
          <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:30%">
            <span class="sr-only">30% Complete</span></div>
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
      </div>
    </div>

    <!-- box 6 -->
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Panel 6 title</h3>
      </div>
      <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet tempus massa. Nam quis purus sit amet augue iaculis dapibus non in nisi. Sed sed volutpat neque. Nulla posuere.</p>
        <p><a class="btn btn-default right" href="#" role="button">Continue &raquo;</a></p>
        </div>
    </div>

  </div><!-- /column 3 (sidebar) -->

</div><!--/row-->

app/views/layouts/_shablony.html.erb
шаблон формы
<!-- <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="bpodl">
          <form role="form">
            <div class="form-group">
              <label for="exampleInputEmail1">Email</label>
              <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Введите email">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Пароль</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Пароль">
            </div>          
            <p><button type="submit" class="btn btn-clear">Войти</button></p>
          </form>
        </div>
      </div> -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_slider.html.erb
<!-- slider -->
<div id="slider" class="carousel slide" data-ride="carousel" data-interval="10000">
  <!-- controls -->
  <ol class="carousel-indicators">
    <li data-target="#slider" data-slide-to="0" class="active"></li>
    <li data-target="#slider" data-slide-to="1"></li>
    <li data-target="#slider" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <!-- slides -->
    <div class="item active">
      <div class="container">
        <div class="carousel-caption" id="cap1">
          <div class='inner-item'>
            <%= link_to image_tag("g10.png", width: "100%"), '#' %>
          </div>
          <p><a class="btn btn-lg btn-danger" href="#" role="button">Подробнее</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="container">
        <div class="carousel-caption" id="cap2">
          <h1 class="classh1">Дарим 10 000 руб. на лазерную коррекцию близорукости <br> по технологии FEMTO</h1>
          <p><a class="btn btn-lg btn-danger" href="#" role="button">Подробнее</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="container">
        <div class="carousel-caption" id="cap3">
          
          <div class="row">
          <!-- <h1 class="classh1"></h1> -->
          <div class="col-md-4">
            <div class='inner-item'>
              <%= link_to image_tag("d10.png", style: "max-width: 250px"), '#' %>
            </div>
          </div>
          <div class="col-md-8" style="vertical-align:middle;">
            <p>Долой очки и контактные линзы! Только с 15 марта по 30 апреля мы дарим вам беспрецедентную скидку - 10 000 рублей на эксимерлазерную коррекцию зрения по технологии Femto LASIK</p>
          </div>        
        </div>

        </div>
      </div>
    </div>
  </div>
  <!-- left-right controls -->
  <a class="left carousel-control" href="#slider" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#slider" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->

app/views/layouts/application0.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lorcenter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>